apiVersion: v1
kind: Secret
metadata:
  name: {{ include "finetuning-service.fullname" . }}-secret
  labels:
    {{- include "finetuning-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ required "Database URL is required" .Values.secrets.databaseUrl | quote }}
  nvidia-keycloak-token-url: {{ required "Nvidia Keycloak Token URL is required" .Values.secrets.nvidiaKeycloakTokenUrl | quote }}
  nvidia-keycloak-client-id: {{ required "Nvidia Keycloak Client ID is required" .Values.secrets.nvidiaKeycloakClientId | quote }}
  nvidia-keycloak-client-secret: {{ required "Nvidia Keycloak Client Secret is required" .Values.secrets.nvidiaKeycloakClientSecret | quote }}
  {{- if .Values.apisix.oidc.enabled }}
  client_id: {{ .Values.apisix.oidc.client_id | quote }}
  client_secret: {{ .Values.apisix.oidc.client_secret | default "" | quote }}
  {{- end }}
