{
 "title": "Gaudi Cards Utilization Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Intel AI for Enterprise Inference",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Total Gaudi Cards in Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(habanalabs_device_config)",
     "legendFormat": "Total Cards"
    }
   ]
  },
  {
   "title": "Available Gaudi Cards in Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(habanalabs_device_config{pod_name=\"\"})",
     "legendFormat": "Total Cards"
    }
   ]
  },
  {
   "title": "Used Gaudi Cards in Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(habanalabs_device_config{pod_name!=\"\"})",
     "legendFormat": "Total Cards"
    }
   ]
  },
  {
   "title": "Utilization Percentage (Used vs. Total)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(habanalabs_device_config{pod_name!=\"\"}) / count(habanalabs_device_config)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-wise Card Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by (pod_name) (habanalabs_device_config{pod_name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node-wise Gaudi Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "count by (node) (habanalabs_device_config)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workloads on Cards",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "habanalabs_device_config{}", "legendFormat": "__auto" }
   ]
  }
 ]
}