apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    app: {{ include "minio.name" . }}
    chart: {{ include "minio.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: api
    protocol: TCP
    name: api
  - port: {{ .Values.service.consolePort }}
    targetPort: console
    protocol: TCP
    name: console
  selector:
    app: {{ include "minio.name" . }}
    release: {{ .Release.Name }}
