# Default values for finetuning-ui
replicaCount: 1

image:
  repository: localhost:5000/finetuning-ui
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: finetuning-ui-tls
      hosts:
        - ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

apisixRoute:
  enabled: true
  name: "finetuning-ui-route"
  hosts:
    - ""
  paths:
    - "/enterprise-ai/ui*"
    - "/enterprise-ai/ui/*"
  priority: 80
  proxyRewrite:
    enabled: false
    regexUri:
      from: "^/enterprise-ai/ui/?(.*)"
      to: "/$1"
  proxyControl:
    enabled: true
    upstreamProxyBufferSize: "16k"
    upstreamProxyBuffers:
      number: 4
      size: "32k"

# Application specific settings
app:
  port: 3000

  # Added ENV variables here
  env:
    - name: NEXT_PUBLIC_AUTH_URL
      value: ""
    - name: NEXT_PUBLIC_FILES_BASE_URL
      value: ""
    - name: NEXT_PUBLIC_DATAPREP_BASE_URL
      value: ""
    - name: NEXT_PUBLIC_FINETUNING_API_URL
      value: ""
    - name: NEXT_TELEMETRY_DISABLED
      value: "1"
    - name: NEXT_PUBLIC_BASE_PATH
      value: ""
    - name: NEXTAUTH_URL
      value: ""
    - name: NEXTAUTH_SECRET
      value: ""
    - name: KEYCLOAK_CLIENT_ID
      value: ""
    - name: KEYCLOAK_ISSUER
      value: ""
  healthChecks:
    enabled: false
