# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: genai-gateway-job-reader  
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genai-gateway-job-reader-binding  
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: genai-gateway-job-reader
  apiGroup: rbac.authorization.k8s.io
